apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzu-winpro-connector
  description: Tanzu WinPro connector test
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=tanzu-winpro-connector'
spec:
  type: service
  lifecycle: experimental
  owner: team-a
